[project]
name = "soumya-work-experience"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt>=1.9.0",
    "duckdb>=1.2.2",
    "pyarrow>=19.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
